print('====== DESAFIO 4 ======')
val = input('Digite algo: ')
print('O tipo é: {}.' .format(type(val)))
print('É numérico: {}.' .format(val.isnumeric()))
print('É alfabético: {}.' .format(val.isalpha()))
print('É ascii: {}.' .format(val.isascii()))
print('É decimal: {}.' .format(val.isdecimal()))
print('É dígito: {}.' .format(val.isdigit()))
print('É identificável: {}.' .format(val.isidentifier()))
print('É minúsculo: {}.' .format(val.islower()))
print('É maiúsculo: {}.' .format(val.isupper()))
print('É capitalizado: {}.' .format(val.istitle()))
print('É alphanúmerico: {}.' .format(val.isalnum()))
print('É espaço: {}.' .format(val.isspace()))
print('É printável: {}.' .format(val.isprintable()))
