print('===== DESAFIO 26 =====')
frase = input('Digite uma frase: ').upper().strip()
print('A letra "A" aparece {} vezes'.format(frase.count('A')))
print(f'A primeira letra "A" aparece na posição {frase.find("A")+1}')
print(f'A última letra "A" aparece na posição {frase.rfind("A")+1}')